version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_DRIVER: ${DB_DRIVER}
    env_file:
      - .env
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./feed.xml:/var/www/test.xml
    ports:
      - 8000:80
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: {}
